### PR TITLE
refactor: match metadata field names with header names

### PR DESCRIPTION
**Pull request by rvolosatovs**
Simplify the API by using consistent naming scheme for headers and metadata fields as was suggested in #22 

Add a few tests as well.

### CODE REVIEW

**Comment by npmccallum** [comment]
@rvolosatovs I find this change slightly confusing because there is no `Content-Hash` header. If we are going to be consistent, then `contentHash` should be `eTag`. But I'm not sure I like that better than what we had to start with. Thoughts?

**Comment by rvolosatovs** [comment]
> @rvolosatovs I find this change slightly confusing because there is no `Content-Hash` header. If we are going to be consistent, then `contentHash` should be `eTag`. But I'm not sure I like that better than what we had to start with. Thoughts?

Yes, I also suggested `eTag` earlier in #1, but did not receive any feedback and decided `contentHash` is more consistent with other fields. I do not mind `eTag`, although it could be a bit confusing, since we're not using the header, since the parameter is specified in the path instead. We might use the header in the future though.

It could also just be named `hash`.
I do think that from the perspective of a person implementing this, the huge difference in naming of the fields and headers is not a good thing and consistency here would improve the usability and make it simpler to understand.

**Comment by npmccallum** [comment]
@rvolosatovs One problem is that we're also abusing `ETag`. It isn't usually supplied on requests and is supposed to have an opaque format. In our case, we're using it on the `PUT` requests and defining its format. It probably isn't a big deal, but something to be aware of.

Without this abuse, we have to read the whole contents just to be able to create the `Meta` just to validate that the `Node` is valid. With this abuse, we can validate the `Node` immediately, which seems more reasonable to me. Should we have a call to go over differences from the design?

**Comment by npmccallum** [comment]
@rvolosatovs Regarding field names, we should be consistent. Either all header names or no header names. I can be convinced either way.

**Comment by rvolosatovs** [comment]
Let's discuss on a call (maybe after standup?), although apart from the metadata naming scheme the only other real differences I noticed were:
- POST -> PUT
- OPTIONS endpoint addition

**Review by npmccallum — DISMISSED** [review]

**Comment by npmccallum** [comment]
@rvolosatovs Please rebase.

**Review by npmccallum — APPROVED** [review]

**Pull request merged**
