### PR TITLE
chore: do not hardcode ciphers

### PR DESCRIPTION
**Pull request by puiterwijk**
We should not hardcode specific ciphers and protocols, but just accept the defaults.
This makes sure that when better ciphers come around, we automatically get them.

Signed-off-by: Patrick Uiterwijk <patrick@profian.com>

### CODE REVIEW

**Review by rvolosatovs — COMMENTED** [review]
Don't we want to disable TLS 1.2?
How are the protocols used by the library chosen to be "safe"?

**Comment by puiterwijk** [comment]
I think they define "safe" as anything that's implemented by rustls, which is a pretty small and decent set.

The problem I was hitting is the whole fact that TLS 1.2 is disabled.
That is still considered to be safe enough at this moment, and the monitoring system I'm trying to use doesn't support TLS1.3 yet, so it's reporting Drawbridge as down.

Additionally, at some point Drawbridge server needs to stop doing its own TLS anyway if we want to run it inside a Keep, at which point these choices are going to be made by Enarx itself, so I'm not sure that this point really matters in the long run.

Though I'd be happy to keep the client-side configuration of ciphers.

**Comment by rjzak** [comment]
TLS 1.3 came out in 2018, 4 years ago. It would seem that there has been plenty of time for various programs, frameworks, etc should have been able to adopt it and move on. What monitoring system are you using, and can use something else?

**Review by rjzak — APPROVED** [review]
Approving, and eventually it'll run in Enarx anyway.

**Pull request merged**
