### PR TITLE
chore: relicense to Apache-2

### PR DESCRIPTION
**Pull request by rjzak**

### CODE REVIEW

**Review by npmccallum — CHANGES_REQUESTED** [review]
Remove copyright assessment. Retain Profian copyright.

**Comment by rjzak** [comment]
@npmccallum I think I did what was asked, but I'm not sure I understand what is meant by removing copyright assessment. Is that the authors line in `Cargo.toml`? Should I change it to "Enarx Project"?

**Comment by rjzak** [comment]
@npmccallum gentle nudge

**Comment by dcmiddle** [comment]
I don't have a maintainer voice here, but from the CCC threads and the comments in the PR, it looks like this is ready to merge.
Nit: I don't think this is material but you may have inadvertently dropped a linefeed in most of the mod.rs files.

cc: @npmccallum

**Pull request merged**
